# Exploring the Dataset: Building the HTTP Events Table

**Goal:** Understand how we go from a raw Apache error log annotation file to a relational database table.

This notebook walks through:
1. Loading `apache` (the raw JSON Lines file containing annotated HTTP event records)
2. Examining what a single record looks like
3. Transforming the data into a Pandas DataFrame
4. Mapping it to our planned `http_events` database table schema

---

**Dataset:** AIT Log Data Set V2.0 — russellmitchell testbed  
**Source:** https://zenodo.org/records/5789064

## 0. Configuration

Set the path to the `russellmitchell/` dataset folder below.  

**Default:** Uses the absolute path to the dataset on this machine:
```
C:/Users/ishaanshetty/DATA-201/russellmitchell/
```

If you're running this on a different machine, update `DATASET_ROOT` to point to your local copy of the `russellmitchell/` folder.

In [1]:
from pathlib import Path

# --- CHANGE THIS if your dataset is in a different location ---
DATASET_ROOT = Path(r"C:/Users/ishaanshetty/DATA-201/russellmitchell")

# The apache error log lives here within the dataset:
# logs/intranet_server/apache2/intranet.smith.russellmitchell.com-error_log.2

# Verify the path exists
if not DATASET_ROOT.exists():
    print(f"ERROR: Dataset not found at: {DATASET_ROOT.resolve()}")
    print("")
    print("Expected directory structure:")
    print("  <workspace>/data-201-security-log-analysis/notebooks/  <-- you are here")
    print("  <workspace>/russellmitchell/                          <-- dataset should be here")
    print("")
    print("Fix: Update DATASET_ROOT above to point to your russellmitchell/ folder.")
else:
    print(f"Dataset found at: {DATASET_ROOT.resolve()}")

Dataset found at: C:\Users\ishaanshetty\DATA-201\russellmitchell

## 1. Load the Raw Apache File

The file `apache` is derived from `logs/intranet_server/apache2/intranet.smith.russellmitchell.com-error_log.2` in the russellmitchell dataset.  
It contains annotated Apache error log records in JSON Lines format — each line is one HTTP event record.  
This is the source for our **`http_events`** database table.

In [1]:
import pandas as pd
import re

annotation_path = DATASET_ROOT / "labels" / "intranet_server" / "logs" / "apache2" / "intranet.smith.russellmitchell.com-error_log.2"
raw_log_path    = DATASET_ROOT / "gather" / "intranet_server" / "logs" / "apache2" / "intranet.smith.russellmitchell.com-error_log.2"

def parse_error_log(annotation_path, raw_log_path):
    # Load annotation (JSON Lines)
    df_ann = pd.read_json(annotation_path, lines=True)
    print(f"Loaded {len(df_ann)} annotation records")
    print(f"\nColumns: {list(df_ann.columns)}")
    print("\nUnique label categories found:")
    all_labels = sorted({lbl for labels in df_ann['labels'] for lbl in labels})
    for i, label in enumerate(all_labels, 1):
        print(f"  {i:2d}. {label}")

    # Parse raw error log: [timestamp] [module:level] [pid N] [client IP:PORT] message
    error_pattern = re.compile(
        r'^\[([^\]]+)\]\s+\[([^\]]+)\](?:\s+\[pid \d+\])?(?:\s+\[client ([^\]]+)\])?\s+(.*)$'
    )
    raw_rows = []
    with open(raw_log_path) as f:
        for lineno, line in enumerate(f, start=1):
            m = error_pattern.match(line.strip())
            if m:
                ts, level, client, msg = m.groups()
                raw_rows.append({'line': lineno, 'timestamp_raw': ts, 'log_level': level,
                                 'client_ip': client.split(':')[0] if client else None,
                                 'message': msg})

    df_raw = pd.DataFrame(raw_rows)
    df_raw['event_timestamp'] = pd.to_datetime(df_raw['timestamp_raw'],
        format='%a %b %d %H:%M:%S.%f %Y', errors='coerce')

    # Join annotation with parsed log fields on line number
    df_merged = df_raw.merge(df_ann[['line','labels','rules']], on='line', how='inner')
    print(f"\nJoined {len(df_merged)} annotated log records with parsed fields")
    return df_merged


df_merged = parse_error_log(annotation_path, raw_log_path)

Loaded 35 annotation records

Columns: ['line', 'labels', 'rules']

Unique label categories found:
   1. attacker_http
   2. dirb
   3. foothold
   4. wpscan

Joined 35 annotated log records with parsed fields

## 2. Examine a Single Record

Let's look at what data exists for one record. We'll pick the first entry to see the full raw structure before we flatten anything.

In [2]:
import json

example_record = df_merged.iloc[0].to_dict()

print("Raw data for record 0:\n")
print(json.dumps(example_record, indent=2))

Raw data for record 0:

{
  "line": 2,
  "labels": [
    "attacker_http",
    "foothold",
    "dirb"
  ],
  "rules": {
    "attacker_http": [
      "attacker.foothold.apache.error",
      "attacker.foothold.apache.access_error"
    ],
    "foothold": [
      "attacker.foothold.apache.error",
      "attacker.foothold.apache.access_error"
    ],
    "dirb": [
      "attacker.dirb.time"
    ]
  }
}

### What do these fields mean?

| Field | What It Is | Example |
|-------|-----------|--------|
| `line` | The original line number from the Apache error log file | `1` |
| `labels` | List of attack-phase tags that apply to this log line | `[attacker_http, foothold, dirb]` |
| `rules` | Dictionary mapping each label to the specific detection rules that matched | `{"dirb": ["attacker.foothold.apache.error.dirb"]}` |

The `labels` field tells us **what kind of attack activity** this log line represents.  
The `rules` field tells us **exactly which detection signature** fired for each label.  
Not all records will have all four label categories — a record tagged only with `wpscan` will only have `wpscan` in its `rules` dict.

## 3. Understand the Label Distribution

The `labels` field categorizes each log line by attack type. Here we count occurrences across all four categories using the fully parsed and joined dataset.

In [4]:
from pandasql import sqldf

df_labels = df_merged.explode('labels').rename(columns={'labels': 'label'})

sqldf("SELECT label, COUNT(*) as total_records FROM df_labels GROUP BY label ORDER BY total_records DESC")

           label  total_records
0  attacker_http             35
1       foothold             35
2           dirb             22
3         wpscan             13

## 4. Find Records by Label

Filter the parsed log table to isolate specific attack stages. Each query returns real log fields alongside attack labels.

In [5]:
# All dirb (directory brute-force) records — shows the IPs and paths being scanned
df_merged[df_merged['labels'].apply(lambda x: 'dirb' in x)]\
    [['event_timestamp', 'client_ip', 'log_level', 'message', 'labels']].head(10)

             event_timestamp          log_level       client_ip                                                                                                                                   message                           labels
0 2022-01-24 03:57:26.698653   authz_core:error  172.19.131.174                                         AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.hta_  [attacker_http, foothold, dirb]
1 2022-01-24 03:57:26.700701   authz_core:error  172.19.131.174                                     AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htaccess  [attacker_http, foothold, dirb]
2 2022-01-24 03:57:26.702901   authz_core:error  172.19.131.174                                    AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htaccess_  [attacker_http, foothold, dirb]
3 2022-01-24 03:57:26.704945   authz_core:error  172.19.131.174                                     AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htpasswd  [attacker_http, foothold, dirb]
4 2022-01-24 03:57:26.707202   authz_core:error  172.19.131.174                                    AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htpasswd_  [attacker_http, foothold, dirb]
5 2022-01-24 03:57:27.362792         php7:error  172.19.131.174                                                script '/var/www/intranet.smith.russellmitchell.com/admin.php' not found or unable to stat  [attacker_http, foothold, dirb]
6 2022-01-24 03:57:32.011505  negotiation:error  172.19.131.174  AH00687: Negotiation: discovered file(s) matching request: /var/www/intranet.smith.russellmitchell.com/index (None could be negotiated).  [attacker_http, foothold, dirb]
7 2022-01-24 03:57:32.118061         php7:error  172.19.131.174                                                 script '/var/www/intranet.smith.russellmitchell.com/info.php' not found or unable to stat  [attacker_http, foothold, dirb]
8 2022-01-24 03:57:34.813751         php7:error  172.19.131.174                                              script '/var/www/intranet.smith.russellmitchell.com/phpinfo.php' not found or unable to stat  [attacker_http, foothold, dirb]
9 2022-01-24 03:57:36.476812   authz_core:error  172.19.131.174                                 AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/server-status  [attacker_http, foothold, dirb]

In [6]:
# Records tagged with both attacker_http and foothold — high-confidence attacker activity
df_merged[df_merged['labels'].apply(lambda x: 'attacker_http' in x and 'foothold' in x)]\
    [['event_timestamp', 'client_ip', 'log_level', 'message', 'labels']].head(10)

             event_timestamp          log_level       client_ip                                                                                                                                   message                           labels
0 2022-01-24 03:57:26.698653   authz_core:error  172.19.131.174                                         AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.hta_  [attacker_http, foothold, dirb]
1 2022-01-24 03:57:26.700701   authz_core:error  172.19.131.174                                     AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htaccess  [attacker_http, foothold, dirb]
2 2022-01-24 03:57:26.702901   authz_core:error  172.19.131.174                                    AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htaccess_  [attacker_http, foothold, dirb]
3 2022-01-24 03:57:26.704945   authz_core:error  172.19.131.174                                     AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htpasswd  [attacker_http, foothold, dirb]
4 2022-01-24 03:57:26.707202   authz_core:error  172.19.131.174                                    AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htpasswd_  [attacker_http, foothold, dirb]
5 2022-01-24 03:57:27.362792         php7:error  172.19.131.174                                                script '/var/www/intranet.smith.russellmitchell.com/admin.php' not found or unable to stat  [attacker_http, foothold, dirb]
6 2022-01-24 03:57:32.011505  negotiation:error  172.19.131.174  AH00687: Negotiation: discovered file(s) matching request: /var/www/intranet.smith.russellmitchell.com/index (None could be negotiated).  [attacker_http, foothold, dirb]
7 2022-01-24 03:57:32.118061         php7:error  172.19.131.174                                                 script '/var/www/intranet.smith.russellmitchell.com/info.php' not found or unable to stat  [attacker_http, foothold, dirb]
8 2022-01-24 03:57:34.813751         php7:error  172.19.131.174                                              script '/var/www/intranet.smith.russellmitchell.com/phpinfo.php' not found or unable to stat  [attacker_http, foothold, dirb]
9 2022-01-24 03:57:36.476812   authz_core:error  172.19.131.174                                 AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/server-status  [attacker_http, foothold, dirb]

In [7]:
# wpscan records — WordPress vulnerability scanning attempts
df_merged[df_merged['labels'].apply(lambda x: 'wpscan' in x)]\
    [['event_timestamp', 'client_ip', 'log_level', 'message', 'labels']].head(10)

             event_timestamp        log_level       client_ip                                                                                                                                                                                                                                                                                                                                      message                             labels
0 2022-01-24 03:57:53.801865       php7:error  172.19.131.174                                                                                                                                                                                   script '/var/www/intranet.smith.russellmitchell.com/searchreplacedb2.php' not found or unable to stat, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
1 2022-01-24 03:57:54.058025  autoindex:error  172.19.131.174                  AH01276: Cannot serve directory /var/www/intranet.smith.russellmitchell.com/wp-content/uploads/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
2 2022-01-24 03:57:54.072251       php7:error  172.19.131.174                                                                                                                                                                                          script '/var/www/intranet.smith.russellmitchell.com/emergency.php' not found or unable to stat, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
3 2022-01-24 03:57:56.986400       php7:error  172.19.131.174  PHP Fatal error:  Uncaught Error: Call to undefined function get_header() in /var/www/intranet.smith.russellmitchell.com/wp-content/themes/go/index.php:15\nStack trace:\n#0 {main}\n  thrown in /var/www/intranet.smith.russellmitchell.com/wp-content/themes/go/index.php on line 15, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
4 2022-01-24 03:58:01.182307       php7:error  172.19.131.174                                                                                                                                                                                           script '/var/www/intranet.smith.russellmitchell.com/timthumb.php' not found or unable to stat, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
5 2022-01-24 03:58:01.182786       php7:error  172.19.131.174                                                                                                                                                                                              script '/var/www/intranet.smith.russellmitchell.com/thumb.php' not found or unable to stat, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
6 2022-01-24 03:58:08.587535       php7:error  172.19.131.174                                                                                                                                                                            script '/var/www/intranet.smith.russellmitchell.com/wp-content/themes/thumb.php' not found or unable to stat, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
7 2022-01-24 03:58:08.590630       php7:error  172.19.131.174                                                                                                                                                                     script '/var/www/intranet.smith.russellmitchell.com/wp-content/themes/!timtimthumb.php' not found or unable to stat, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
8 2022-01-24 03:58:08.591131       php7:error  172.19.131.174                                                                                                                                                                        script '/var/www/intranet.smith.russellmitchell.com/wp-content/themes/!timthumb.php' not found or unable to stat, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]
9 2022-01-24 03:58:09.170391       php7:error  172.19.131.174                                                                                                                                                                                script '/var/www/intranet.smith.russellmitchell.com/wp-content/timthumb.php' not found or unable to stat, referer: https://intranet.smith.russellmitchell.com  [attacker_http, foothold, wpscan]

## 5. Records Carrying Only One Label

Lines that triggered exactly one detection rule — useful for validating individual signatures in isolation.

In [8]:
df_single = df_merged[df_merged['labels'].apply(len) == 1].copy()
df_single['label'] = df_single['labels'].apply(lambda x: x[0])

df_single.groupby('label').size().reset_index(name='total').sort_values('total', ascending=False)

Empty DataFrame
Columns: [label, total]
Index: []

In [9]:
# Show the actual log entries for single-label records
df_single[['event_timestamp', 'client_ip', 'log_level', 'message', 'label']].head(10)

Empty DataFrame
Columns: [event_timestamp, log_level, client_ip, message, label]
Index: []

## 6. What Signatures Does Each Label Fire?

The `rules` field contains a nested dictionary of signature matches. Flatten it to document all sub-fields and how they map to `http.request.sig_match` in our schema.

In [10]:
df_flat = df_merged['rules'].apply(lambda r: list(r.keys()) if isinstance(r, dict) else [])\
                             .explode().dropna()

# Unique signatures fired per label
sig_rows = []
for _, row in df_merged.iterrows():
    if isinstance(row['rules'], dict):
        for label, sigs in row['rules'].items():
            for sig in sigs:
                sig_rows.append({'label': label, 'signature': sig})

df_sigs = pd.DataFrame(sig_rows).drop_duplicates()
df_sigs.sort_values('label')

           label                                 signature
0  attacker_http            attacker.foothold.apache.error
1  attacker_http     attacker.foothold.apache.access_error
2  attacker_http  attacker.foothold.apache.error_substring
3           dirb                        attacker.dirb.time
4       foothold            attacker.foothold.apache.error
5       foothold     attacker.foothold.apache.access_error
6       foothold  attacker.foothold.apache.error_substring
7         wpscan                      attacker.wpscan.time

## 7. Mapping to the Database Schema

Here's how this data maps to our planned **`http_events`** table in PostgreSQL:

| Raw Field | DB Column | SQL Type | Notes |
|-----------|-----------|----------|-------|
| *(auto-generated)* | `http_event_id` | `SERIAL PRIMARY KEY` | Auto-incrementing ID |
| `line` | `event_id` | `INTEGER NOT NULL` | Original line number from the log file |
| `event_timestamp` | `event_timestamp` | `TIMESTAMP` | Parsed from raw log |
| `log_level` | `log_level` | `VARCHAR(50)` | e.g. `auth_basic:error` |
| `client_ip` | `client_ip` | `INET` | Attacker IP address |
| `message` | `message` | `TEXT` | Full log message |
| `labels` | `http_event_category` | `TEXT[]` | Array of attack-phase labels |
| `rules` | `http_signature_matches` | `JSONB` | Full nested signature match dictionary |
| *(auto-generated)* | `created_at` | `TIMESTAMP DEFAULT CURRENT_TIMESTAMP` | Added at insert time |

### The SQL `CREATE TABLE` statement:

```sql
CREATE TABLE http_events (
    http_event_id          SERIAL PRIMARY KEY,
    event_id               INTEGER NOT NULL,
    event_timestamp        TIMESTAMP,
    log_level              VARCHAR(50),
    client_ip              INET,
    message                TEXT,
    http_event_category    TEXT[],
    http_signature_matches JSONB,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

In [11]:
# Preview of the http_events table as it will look in PostgreSQL
db_preview = df_merged[['line', 'event_timestamp', 'log_level', 'client_ip', 'message', 'labels', 'rules']].copy()
db_preview.columns = ['event_id', 'event_timestamp', 'log_level', 'client_ip', 'message', 'http_event_category', 'http_signature_matches']
db_preview.head(10)

   http_event_id  event_id            event_timestamp          log_level       client_ip                                                                                                                                   message              http_event_category                                                                                                                                                                                                   http_signature_matches
0              1         2 2022-01-24 03:57:26.698653   authz_core:error  172.19.131.174                                         AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.hta_  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
1              2         3 2022-01-24 03:57:26.700701   authz_core:error  172.19.131.174                                     AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htaccess  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
2              3         4 2022-01-24 03:57:26.702901   authz_core:error  172.19.131.174                                    AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htaccess_  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
3              4         5 2022-01-24 03:57:26.704945   authz_core:error  172.19.131.174                                     AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htpasswd  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
4              5         6 2022-01-24 03:57:26.707202   authz_core:error  172.19.131.174                                    AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/.htpasswd_  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
5              6         7 2022-01-24 03:57:27.362792         php7:error  172.19.131.174                                                script '/var/www/intranet.smith.russellmitchell.com/admin.php' not found or unable to stat  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
6              7         8 2022-01-24 03:57:32.011505  negotiation:error  172.19.131.174  AH00687: Negotiation: discovered file(s) matching request: /var/www/intranet.smith.russellmitchell.com/index (None could be negotiated).  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
7              8         9 2022-01-24 03:57:32.118061         php7:error  172.19.131.174                                                 script '/var/www/intranet.smith.russellmitchell.com/info.php' not found or unable to stat  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
8              9        10 2022-01-24 03:57:34.813751         php7:error  172.19.131.174                                              script '/var/www/intranet.smith.russellmitchell.com/phpinfo.php' not found or unable to stat  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}
9             10        11 2022-01-24 03:57:36.476812   authz_core:error  172.19.131.174                                 AH01630: client denied by server configuration: /var/www/intranet.smith.russellmitchell.com/server-status  [attacker_http, foothold, dirb]  {'attacker_http': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'foothold': ['attacker.foothold.apache.error', 'attacker.foothold.apache.access_error'], 'dirb': ['attacker.dirb.time']}